### ISSUE TITLE
Generate citations

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/library_project_scripting#19]
**Describe the solution you'd like**
Allow users to generate citations from individual items.

**Additional context**
Dependent upon existing data cleanliness. Additionally, would have to decide upon the citation style. I'm not sure we want to support multiple different styles of citations.

What does this look like? An exported document? Copy/paste field in the application?

**Comment by helrond** [comment]
I'd strongly suggest, if we want to move forward on this issue, that we think about this as exposing fields to a citation manager like Zotero. This would likely mean enhancing the `meta` tags, which would in term mean changes to `make_pages.py` to place additional data in the frontmatter. 

See https://www.zotero.org/support/dev/exposing_metadata
