### ISSUE TITLE
Combine resource records with attached agents, subjects, and containers into single file

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/library_project_scripting#21]
**Is your feature request related to a problem? Please describe.**
Agents, subject, and containers aren't browsable objects in the MVP. However, we want these records to be searchable and show up as linked to resources in search results.

**Describe the solution you'd like**
 Working theory is that we should combine these with resource records into a single JSON file and then serve the data from a single location. We cannot get rid of agents and subjects once combined, since they will be reused for multiple resource records.

**Comment by helrond** [comment]
This *might* not be necessary. I'd suggest making this a subset of #24 and whoever's implementing that can make a call about whether this step is necessary or not.

**Comment by p-galligan** [comment]
Added as additional research to #24.
