### ISSUE TITLE
Delete Script needs to remove resource records that do not start with FA or AC identifier

### ISSUE THREAD

**Issue by kemartin2015** [RockefellerArchiveCenter/library_project_scripting#3]
The delete script needs to remove library resource records starting with the LI identifier from AS.

**Comment by helrond** [comment]
Another way (and perhaps more foolproof) way to do this would be to iterate over the exported resource records (which would be particularly useful if the filenames were AS ids) and used that as a list to delete from. That way you're not deleting something you didn't export by mistake if the logic in the export and delete scripts isn't identical (and someone hasn't tweaked an identifier in the meantime).
