### ISSUE TITLE
Authors display all agents

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/library_project_scripting#56]
**Describe the bug**
An author search currently searches all agents, including subjects.

**Expected behavior**
Author search should only search a combined list of agents with the `aut` or `edt` relators.

**Comment by helrond** [comment]
One potential issue here is that not all linked agents have a `relator`. It may be easier just to include any linked agent with a `role` of `creator`

**Comment by p-galligan** [comment]
I've got a working mockup of search including authors and editors, but I can just match on creator instead.
