### ISSUE TITLE
Add search tool tips

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/library_project_scripting#62]
**Is your feature request related to a problem? Please describe.**
Not a problem per se, but lunr search doesn't match on parts of words automatically. Therefore, if you search `boa`, you won't get any hits for `board`. However, you can add a `*` to the beginning or front of a search string to match words containing that string. 

I'm not sure this will be obvious to the average user. 

**Describe the solution you'd like**
I think we should wait until after user testing to see if this is an actual report problem, but a quick tooltip about adding wildcards to searches could be helpful based on results.

**Comment by helrond** [comment]
We didn't really get much data which indicated this is a thing people want/need in user testing so I'm closing this.
