### ISSUE TITLE
Site is missing `url` and `baseurl` settings in the config

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/library_project_scripting#82]
**Describe the bug**
The url and baseurl fields are missing in `_config.yml`.

**Additional context**
Need to add these before going live with the site. Also effects links to items in Aeon.

**Comment by helrond** [comment]
Is there a way to do this that will work for both dev and prod, since they'll be hosted at different URLs?

**Comment by p-galligan** [comment]
Looks like there might be a way: https://jekyllrb.com/news/2016/10/06/jekyll-3-3-is-here/

**Comment by helrond** [comment]
Hmmm that only applies to running the development server, not a dev instance that's built. But it looks like you could do it with a conditional statement https://jekyllrb.com/docs/configuration/environments/
