### ISSUE TITLE
Separate built site from build code

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/library_project_scripting#98]
**Is your feature request related to a problem? Please describe.**
The built site and the build code currently live in a fairly busy directory/hierarchy and that can get confusing to navigate.

**Describe the solution you'd like**
Separate the built end product from the code that does the building.

**Additional context**
Relatively standard Jekyll implementation, so we'd have to carefully document any changes that we make.

**Comment by helrond** [comment]
I've recently come back to this project after having been away from it for a few months, and I found the structure to be pretty navigable. A lot of that has to do with the fact that it's a standard Jekyll structure. I'd propose we leave as-is. Thoughts, @p-galligan?

**Comment by HaSistrunk** [comment]
@p-galligan can we close this issue?

**Comment by p-galligan** [comment]
Yes, sorry, I didn't see this @ from last week. I'll close
