### ISSUE TITLE
Align SASS libraries to general RAC and DIMES SASS

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/library_project_scripting#99]
**Is your feature request related to a problem? Please describe.**
SASS libraries are already out of date from the DIMES implementation.

**Describe the solution you'd like**
Align with updated libraries and possibly submodule to another repository that contains the most up to date SASS for easy updates in the future.

**Comment by HaSistrunk** [comment]
This was fixed with PR #188
